# Generated by Django 5.1.2 on 2024-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="The_Player_Icon.png", null=True, upload_to=""
            ),
        ),
    ]
